//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChargeInterface.WebReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sdfyy.cn/", ConfigurationName="WebReference.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdfyy.cn/AppApplyLis", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AppApplyLis(string inparam1, string inparam2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdfyy.cn/AppApplyUpYkrk", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AppApplyUpYkrk(string charge_code, string serial, decimal buy_price, decimal buy_amt, string eff_date, string manu_no, string rept_no, string supply_coop, string manufacture, string license_no, string purchaser, string checker, string group_no, string accept_man);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdfyy.cn/AppApplyUpMzyfCk", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AppApplyUpMzyfCk(string prescriptionno, int win_no, string py_id, string py_date, string fy_id, string group_no, int ypmxs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdfyy.cn/AppApplyPivasLayResiByCarry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AppApplyPivasLayResiByCarry(decimal parent_no, System.DateTime occ_time, int carry_amount, string p_operator);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdfyy.cn/GetHisData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetHisData(string inputxml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdfyy.cn/GetLabMaster", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetLabMaster(string inpatient_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdfyy.cn/GetLabResult", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetLabResult(string TestNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdfyy.cn/GetYjkLisResult", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetYjkLisResult(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdfyy.cn/SendSms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SendSms(string mobileno, long smID, long srcID, string msg, string sendTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdfyy.cn/InputFee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InputFee(string pxml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdfyy.cn/getPatient", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ChargeInterface.WebReference.yh_patient getPatient(string mrn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdfyy.cn/getPatient_series", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ChargeInterface.WebReference.yh_patient getPatient_series(string mrn, int series);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdfyy.cn/getOutPatient", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ChargeInterface.WebReference.yh_patient getOutPatient(string mrn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdfyy.cn/getPatientsByWard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ChargeInterface.WebReference.yh_patient[] getPatientsByWard(string wardCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdfyy.cn/getDepts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ChargeInterface.WebReference.yh_dept[] getDepts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdfyy.cn/getWards", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ChargeInterface.WebReference.yh_ward[] getWards(string deptCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdfyy.cn/getWard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getWard(string wardCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdfyy.cn/getUsers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ChargeInterface.WebReference.yh_user[] getUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdfyy.cn/getUsersWard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ChargeInterface.WebReference.yh_user[] getUsersWard(string wardCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdfyy.cn/getUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ChargeInterface.WebReference.yh_user getUser(string userCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdfyy.cn/GetOutPatients", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetOutPatients(string dis_date_s, string dis_date_e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdfyy.cn/GetPatientInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetPatientInfo(string xmlstr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdfyy.cn/GetTjPatientId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetTjPatientId(string patient_xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdfyy.cn/AppApply", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void AppApply(int trade, string strInput, string strOutput, ref System.Data.DataSet ds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdfyy.cn/AppApplyTran", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int AppApplyTran(string strCon, object[] sqlList);
        
        // CODEGEN: 参数“input”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlArrayItemAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://sdfyy.cn/PubProc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ChargeInterface.WebReference.PubProcResponse PubProc(ChargeInterface.WebReference.PubProcRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdfyy.cn/GetPtInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetPtInfo(string xml);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sdfyy.cn/")]
    public partial class yh_patient : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string patientIDField;
        
        private int seriesField;
        
        private string mrnField;
        
        private string wardCodeField;
        
        private string bedNoField;
        
        private string nameField;
        
        private System.DateTime birthdayField;
        
        private string admissionTimeField;
        
        private string disTimeField;
        
        private string admissionWardTimeField;
        
        private string nursingLevelField;
        
        private string diagnosisField;
        
        private string conditionField;
        
        private string doctorCodeField;
        
        private string doctorNameField;
        
        private float heightField;
        
        private double sumCostField;
        
        private double prePaymentsField;
        
        private double selfPaymentsField;
        
        private int arrearFlagField;
        
        private string allergyHistoryField;
        
        private string insuranceTypeField;
        
        private string deptCodeField;
        
        private int sexField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string patientID {
            get {
                return this.patientIDField;
            }
            set {
                this.patientIDField = value;
                this.RaisePropertyChanged("patientID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int series {
            get {
                return this.seriesField;
            }
            set {
                this.seriesField = value;
                this.RaisePropertyChanged("series");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string mrn {
            get {
                return this.mrnField;
            }
            set {
                this.mrnField = value;
                this.RaisePropertyChanged("mrn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string wardCode {
            get {
                return this.wardCodeField;
            }
            set {
                this.wardCodeField = value;
                this.RaisePropertyChanged("wardCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string bedNo {
            get {
                return this.bedNoField;
            }
            set {
                this.bedNoField = value;
                this.RaisePropertyChanged("bedNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime birthday {
            get {
                return this.birthdayField;
            }
            set {
                this.birthdayField = value;
                this.RaisePropertyChanged("birthday");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string admissionTime {
            get {
                return this.admissionTimeField;
            }
            set {
                this.admissionTimeField = value;
                this.RaisePropertyChanged("admissionTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string disTime {
            get {
                return this.disTimeField;
            }
            set {
                this.disTimeField = value;
                this.RaisePropertyChanged("disTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string admissionWardTime {
            get {
                return this.admissionWardTimeField;
            }
            set {
                this.admissionWardTimeField = value;
                this.RaisePropertyChanged("admissionWardTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string nursingLevel {
            get {
                return this.nursingLevelField;
            }
            set {
                this.nursingLevelField = value;
                this.RaisePropertyChanged("nursingLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string diagnosis {
            get {
                return this.diagnosisField;
            }
            set {
                this.diagnosisField = value;
                this.RaisePropertyChanged("diagnosis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
                this.RaisePropertyChanged("condition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string doctorCode {
            get {
                return this.doctorCodeField;
            }
            set {
                this.doctorCodeField = value;
                this.RaisePropertyChanged("doctorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string doctorName {
            get {
                return this.doctorNameField;
            }
            set {
                this.doctorNameField = value;
                this.RaisePropertyChanged("doctorName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public float height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("height");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public double sumCost {
            get {
                return this.sumCostField;
            }
            set {
                this.sumCostField = value;
                this.RaisePropertyChanged("sumCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public double prePayments {
            get {
                return this.prePaymentsField;
            }
            set {
                this.prePaymentsField = value;
                this.RaisePropertyChanged("prePayments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public double selfPayments {
            get {
                return this.selfPaymentsField;
            }
            set {
                this.selfPaymentsField = value;
                this.RaisePropertyChanged("selfPayments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int arrearFlag {
            get {
                return this.arrearFlagField;
            }
            set {
                this.arrearFlagField = value;
                this.RaisePropertyChanged("arrearFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string allergyHistory {
            get {
                return this.allergyHistoryField;
            }
            set {
                this.allergyHistoryField = value;
                this.RaisePropertyChanged("allergyHistory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string insuranceType {
            get {
                return this.insuranceTypeField;
            }
            set {
                this.insuranceTypeField = value;
                this.RaisePropertyChanged("insuranceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string deptCode {
            get {
                return this.deptCodeField;
            }
            set {
                this.deptCodeField = value;
                this.RaisePropertyChanged("deptCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public int sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
                this.RaisePropertyChanged("sex");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sdfyy.cn/")]
    public partial class yh_user : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string userCodeField;
        
        private string deptCodeField;
        
        private string wardCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string userCode {
            get {
                return this.userCodeField;
            }
            set {
                this.userCodeField = value;
                this.RaisePropertyChanged("userCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string deptCode {
            get {
                return this.deptCodeField;
            }
            set {
                this.deptCodeField = value;
                this.RaisePropertyChanged("deptCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string wardCode {
            get {
                return this.wardCodeField;
            }
            set {
                this.wardCodeField = value;
                this.RaisePropertyChanged("wardCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sdfyy.cn/")]
    public partial class yh_ward : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string wardCodeField;
        
        private string deptCodeField;
        
        private string wardNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string wardCode {
            get {
                return this.wardCodeField;
            }
            set {
                this.wardCodeField = value;
                this.RaisePropertyChanged("wardCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string deptCode {
            get {
                return this.deptCodeField;
            }
            set {
                this.deptCodeField = value;
                this.RaisePropertyChanged("deptCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string wardName {
            get {
                return this.wardNameField;
            }
            set {
                this.wardNameField = value;
                this.RaisePropertyChanged("wardName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sdfyy.cn/")]
    public partial class yh_dept : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string deptCodeField;
        
        private string deptNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string deptCode {
            get {
                return this.deptCodeField;
            }
            set {
                this.deptCodeField = value;
                this.RaisePropertyChanged("deptCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string deptName {
            get {
                return this.deptNameField;
            }
            set {
                this.deptNameField = value;
                this.RaisePropertyChanged("deptName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PubProc", WrapperNamespace="http://sdfyy.cn/", IsWrapped=true)]
    public partial class PubProcRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdfyy.cn/", Order=0)]
        public int trade;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdfyy.cn/", Order=1)]
        public string procname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdfyy.cn/", Order=2)]
        public string sqlConnection;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdfyy.cn/", Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfAnyType")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public object[][] input;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdfyy.cn/", Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfAnyType")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public object[][] output;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdfyy.cn/", Order=5)]
        public string errmsg;
        
        public PubProcRequest() {
        }
        
        public PubProcRequest(int trade, string procname, string sqlConnection, object[][] input, object[][] output, string errmsg) {
            this.trade = trade;
            this.procname = procname;
            this.sqlConnection = sqlConnection;
            this.input = input;
            this.output = output;
            this.errmsg = errmsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PubProcResponse", WrapperNamespace="http://sdfyy.cn/", IsWrapped=true)]
    public partial class PubProcResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdfyy.cn/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfAnyType")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public object[][] output;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdfyy.cn/", Order=1)]
        public string errmsg;
        
        public PubProcResponse() {
        }
        
        public PubProcResponse(object[][] output, string errmsg) {
            this.output = output;
            this.errmsg = errmsg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : ChargeInterface.WebReference.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<ChargeInterface.WebReference.ServiceSoap>, ChargeInterface.WebReference.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AppApplyLis(string inparam1, string inparam2) {
            return base.Channel.AppApplyLis(inparam1, inparam2);
        }
        
        public string AppApplyUpYkrk(string charge_code, string serial, decimal buy_price, decimal buy_amt, string eff_date, string manu_no, string rept_no, string supply_coop, string manufacture, string license_no, string purchaser, string checker, string group_no, string accept_man) {
            return base.Channel.AppApplyUpYkrk(charge_code, serial, buy_price, buy_amt, eff_date, manu_no, rept_no, supply_coop, manufacture, license_no, purchaser, checker, group_no, accept_man);
        }
        
        public string AppApplyUpMzyfCk(string prescriptionno, int win_no, string py_id, string py_date, string fy_id, string group_no, int ypmxs) {
            return base.Channel.AppApplyUpMzyfCk(prescriptionno, win_no, py_id, py_date, fy_id, group_no, ypmxs);
        }
        
        public string AppApplyPivasLayResiByCarry(decimal parent_no, System.DateTime occ_time, int carry_amount, string p_operator) {
            return base.Channel.AppApplyPivasLayResiByCarry(parent_no, occ_time, carry_amount, p_operator);
        }
        
        public string[] GetHisData(string inputxml) {
            return base.Channel.GetHisData(inputxml);
        }
        
        public string[] GetLabMaster(string inpatient_no) {
            return base.Channel.GetLabMaster(inpatient_no);
        }
        
        public string[] GetLabResult(string TestNo) {
            return base.Channel.GetLabResult(TestNo);
        }
        
        public string GetYjkLisResult(string xml) {
            return base.Channel.GetYjkLisResult(xml);
        }
        
        public int SendSms(string mobileno, long smID, long srcID, string msg, string sendTime) {
            return base.Channel.SendSms(mobileno, smID, srcID, msg, sendTime);
        }
        
        public string InputFee(string pxml) {
            return base.Channel.InputFee(pxml);
        }
        
        public ChargeInterface.WebReference.yh_patient getPatient(string mrn) {
            return base.Channel.getPatient(mrn);
        }
        
        public ChargeInterface.WebReference.yh_patient getPatient_series(string mrn, int series) {
            return base.Channel.getPatient_series(mrn, series);
        }
        
        public ChargeInterface.WebReference.yh_patient getOutPatient(string mrn) {
            return base.Channel.getOutPatient(mrn);
        }
        
        public ChargeInterface.WebReference.yh_patient[] getPatientsByWard(string wardCode) {
            return base.Channel.getPatientsByWard(wardCode);
        }
        
        public ChargeInterface.WebReference.yh_dept[] getDepts() {
            return base.Channel.getDepts();
        }
        
        public ChargeInterface.WebReference.yh_ward[] getWards(string deptCode) {
            return base.Channel.getWards(deptCode);
        }
        
        public string getWard(string wardCode) {
            return base.Channel.getWard(wardCode);
        }
        
        public ChargeInterface.WebReference.yh_user[] getUsers() {
            return base.Channel.getUsers();
        }
        
        public ChargeInterface.WebReference.yh_user[] getUsersWard(string wardCode) {
            return base.Channel.getUsersWard(wardCode);
        }
        
        public ChargeInterface.WebReference.yh_user getUser(string userCode) {
            return base.Channel.getUser(userCode);
        }
        
        public System.Data.DataSet GetOutPatients(string dis_date_s, string dis_date_e) {
            return base.Channel.GetOutPatients(dis_date_s, dis_date_e);
        }
        
        public string GetPatientInfo(string xmlstr) {
            return base.Channel.GetPatientInfo(xmlstr);
        }
        
        public string GetTjPatientId(string patient_xml) {
            return base.Channel.GetTjPatientId(patient_xml);
        }
        
        public void AppApply(int trade, string strInput, string strOutput, ref System.Data.DataSet ds) {
            base.Channel.AppApply(trade, strInput, strOutput, ref ds);
        }
        
        public int AppApplyTran(string strCon, object[] sqlList) {
            return base.Channel.AppApplyTran(strCon, sqlList);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChargeInterface.WebReference.PubProcResponse ChargeInterface.WebReference.ServiceSoap.PubProc(ChargeInterface.WebReference.PubProcRequest request) {
            return base.Channel.PubProc(request);
        }
        
        public void PubProc(int trade, string procname, string sqlConnection, object[][] input, ref object[][] output, ref string errmsg) {
            ChargeInterface.WebReference.PubProcRequest inValue = new ChargeInterface.WebReference.PubProcRequest();
            inValue.trade = trade;
            inValue.procname = procname;
            inValue.sqlConnection = sqlConnection;
            inValue.input = input;
            inValue.output = output;
            inValue.errmsg = errmsg;
            ChargeInterface.WebReference.PubProcResponse retVal = ((ChargeInterface.WebReference.ServiceSoap)(this)).PubProc(inValue);
            output = retVal.output;
            errmsg = retVal.errmsg;
        }
        
        public string GetPtInfo(string xml) {
            return base.Channel.GetPtInfo(xml);
        }
    }
}
