//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransTuiYao.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IHisService")]
    public interface IHisService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHisService/HelloWorld", ReplyAction="http://tempuri.org/IHisService/HelloWorldResponse")]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHisService/HelloWorld", ReplyAction="http://tempuri.org/IHisService/HelloWorldResponse")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHisService/HisTransData", ReplyAction="http://tempuri.org/IHisService/HisTransDataResponse")]
        string HisTransData(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHisService/HisTransData", ReplyAction="http://tempuri.org/IHisService/HisTransDataResponse")]
        System.Threading.Tasks.Task<string> HisTransDataAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHisService/PivasTransData", ReplyAction="http://tempuri.org/IHisService/PivasTransDataResponse")]
        string PivasTransData(string opType, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHisService/PivasTransData", ReplyAction="http://tempuri.org/IHisService/PivasTransDataResponse")]
        System.Threading.Tasks.Task<string> PivasTransDataAsync(string opType, string value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHisServiceChannel : TransTuiYao.ServiceReference1.IHisService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HisServiceClient : System.ServiceModel.ClientBase<TransTuiYao.ServiceReference1.IHisService>, TransTuiYao.ServiceReference1.IHisService {
        
        public HisServiceClient() {
        }
        
        public HisServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HisServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HisServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HisServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public string HisTransData(string value) {
            return base.Channel.HisTransData(value);
        }
        
        public System.Threading.Tasks.Task<string> HisTransDataAsync(string value) {
            return base.Channel.HisTransDataAsync(value);
        }
        
        public string PivasTransData(string opType, string value) {
            return base.Channel.PivasTransData(opType, value);
        }
        
        public System.Threading.Tasks.Task<string> PivasTransDataAsync(string opType, string value) {
            return base.Channel.PivasTransDataAsync(opType, value);
        }
    }
}
