//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransTuiYao.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.UpInterfaceSoap")]
    public interface UpInterfaceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 labels 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LabelInfo", ReplyAction="*")]
        TransTuiYao.ServiceReference2.LabelInfoResponse LabelInfo(TransTuiYao.ServiceReference2.LabelInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LabelInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<TransTuiYao.ServiceReference2.LabelInfoResponse> LabelInfoAsync(TransTuiYao.ServiceReference2.LabelInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LabelInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LabelInfo", Namespace="http://tempuri.org/", Order=0)]
        public TransTuiYao.ServiceReference2.LabelInfoRequestBody Body;
        
        public LabelInfoRequest() {
        }
        
        public LabelInfoRequest(TransTuiYao.ServiceReference2.LabelInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LabelInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object labels;
        
        public LabelInfoRequestBody() {
        }
        
        public LabelInfoRequestBody(object labels) {
            this.labels = labels;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LabelInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LabelInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public TransTuiYao.ServiceReference2.LabelInfoResponseBody Body;
        
        public LabelInfoResponse() {
        }
        
        public LabelInfoResponse(TransTuiYao.ServiceReference2.LabelInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LabelInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LabelInfoResult;
        
        public LabelInfoResponseBody() {
        }
        
        public LabelInfoResponseBody(string LabelInfoResult) {
            this.LabelInfoResult = LabelInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UpInterfaceSoapChannel : TransTuiYao.ServiceReference2.UpInterfaceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpInterfaceSoapClient : System.ServiceModel.ClientBase<TransTuiYao.ServiceReference2.UpInterfaceSoap>, TransTuiYao.ServiceReference2.UpInterfaceSoap {
        
        public UpInterfaceSoapClient() {
        }
        
        public UpInterfaceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UpInterfaceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpInterfaceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpInterfaceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransTuiYao.ServiceReference2.LabelInfoResponse TransTuiYao.ServiceReference2.UpInterfaceSoap.LabelInfo(TransTuiYao.ServiceReference2.LabelInfoRequest request) {
            return base.Channel.LabelInfo(request);
        }
        
        public string LabelInfo(object labels) {
            TransTuiYao.ServiceReference2.LabelInfoRequest inValue = new TransTuiYao.ServiceReference2.LabelInfoRequest();
            inValue.Body = new TransTuiYao.ServiceReference2.LabelInfoRequestBody();
            inValue.Body.labels = labels;
            TransTuiYao.ServiceReference2.LabelInfoResponse retVal = ((TransTuiYao.ServiceReference2.UpInterfaceSoap)(this)).LabelInfo(inValue);
            return retVal.Body.LabelInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TransTuiYao.ServiceReference2.LabelInfoResponse> TransTuiYao.ServiceReference2.UpInterfaceSoap.LabelInfoAsync(TransTuiYao.ServiceReference2.LabelInfoRequest request) {
            return base.Channel.LabelInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TransTuiYao.ServiceReference2.LabelInfoResponse> LabelInfoAsync(object labels) {
            TransTuiYao.ServiceReference2.LabelInfoRequest inValue = new TransTuiYao.ServiceReference2.LabelInfoRequest();
            inValue.Body = new TransTuiYao.ServiceReference2.LabelInfoRequestBody();
            inValue.Body.labels = labels;
            return ((TransTuiYao.ServiceReference2.UpInterfaceSoap)(this)).LabelInfoAsync(inValue);
        }
    }
}
