//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using ChargeInterface.Properties;
using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// 此源代码由 wsdl 自动生成, Version=4.6.1055.0。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="SPDWebServiceSoap", Namespace="http://tempuri.org/")]
public partial class SPDWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback DataExchangeOperationCompleted;
    
    private System.Threading.SendOrPostCallback SyncDrugBasicInfoOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetDrugExtenderInfoOperationCompleted;
    
    private System.Threading.SendOrPostCallback SynchDeptPharmacyDrugRelationOperationCompleted;
    
    private System.Threading.SendOrPostCallback SynchDrugPriceOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetDrugInventoryOperationCompleted;
    
    private System.Threading.SendOrPostCallback QueryOPDrugWindowRequestOperationCompleted;
    
    private System.Threading.SendOrPostCallback QueryOPDrugSendRequestOperationCompleted;
    
    private System.Threading.SendOrPostCallback SyncOPFeeReturnStatusOperationCompleted;
    
    private System.Threading.SendOrPostCallback SyncOPDrugSendRequestOperationCompleted;
    
    private System.Threading.SendOrPostCallback QueryOPDrugReturnRequestOperationCompleted;
    
    private System.Threading.SendOrPostCallback SynchOPDrugReturnRequestOperationCompleted;
    
    private System.Threading.SendOrPostCallback QueryIPDrugSendRequestOperationCompleted;
    
    private System.Threading.SendOrPostCallback SynchIPDrugSendRequestOperationCompleted;
    
    private System.Threading.SendOrPostCallback SynchCancelDrugSendRequestsOperationCompleted;
    
    private System.Threading.SendOrPostCallback QueryIPDrugReturnRequestOperationCompleted;
    
    private System.Threading.SendOrPostCallback SynchIPDrugReturnRequestOperationCompleted;
    
    private System.Threading.SendOrPostCallback SynchCancelDrugReturnRequestsOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetInPatientInfoOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetIPDrugOrderOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetDiagnosisOperationCompleted;
    
    private System.Threading.SendOrPostCallback UpdateFPHOperationCompleted;
    
    private System.Threading.SendOrPostCallback YPZDBZOperationCompleted;
    
    /// <remarks/>
    public SPDWebService() {
        this.Url = Settings.Default.SHLYD_Service_Address;//从配置文件中加载服务地址
        //this.Url = "http://172.20.10.168:8077/SPDWebService.asmx";//新his接口服务器地址
        //this.Url = "http://172.20.10.167:8091/SPDWebService.asmx";//旧his接口服务器地址
    }
    
    /// <remarks/>
    public event DataExchangeCompletedEventHandler DataExchangeCompleted;
    
    /// <remarks/>
    public event SyncDrugBasicInfoCompletedEventHandler SyncDrugBasicInfoCompleted;
    
    /// <remarks/>
    public event GetDrugExtenderInfoCompletedEventHandler GetDrugExtenderInfoCompleted;
    
    /// <remarks/>
    public event SynchDeptPharmacyDrugRelationCompletedEventHandler SynchDeptPharmacyDrugRelationCompleted;
    
    /// <remarks/>
    public event SynchDrugPriceCompletedEventHandler SynchDrugPriceCompleted;
    
    /// <remarks/>
    public event GetDrugInventoryCompletedEventHandler GetDrugInventoryCompleted;
    
    /// <remarks/>
    public event QueryOPDrugWindowRequestCompletedEventHandler QueryOPDrugWindowRequestCompleted;
    
    /// <remarks/>
    public event QueryOPDrugSendRequestCompletedEventHandler QueryOPDrugSendRequestCompleted;
    
    /// <remarks/>
    public event SyncOPFeeReturnStatusCompletedEventHandler SyncOPFeeReturnStatusCompleted;
    
    /// <remarks/>
    public event SyncOPDrugSendRequestCompletedEventHandler SyncOPDrugSendRequestCompleted;
    
    /// <remarks/>
    public event QueryOPDrugReturnRequestCompletedEventHandler QueryOPDrugReturnRequestCompleted;
    
    /// <remarks/>
    public event SynchOPDrugReturnRequestCompletedEventHandler SynchOPDrugReturnRequestCompleted;
    
    /// <remarks/>
    public event QueryIPDrugSendRequestCompletedEventHandler QueryIPDrugSendRequestCompleted;
    
    /// <remarks/>
    public event SynchIPDrugSendRequestCompletedEventHandler SynchIPDrugSendRequestCompleted;
    
    /// <remarks/>
    public event SynchCancelDrugSendRequestsCompletedEventHandler SynchCancelDrugSendRequestsCompleted;
    
    /// <remarks/>
    public event QueryIPDrugReturnRequestCompletedEventHandler QueryIPDrugReturnRequestCompleted;
    
    /// <remarks/>
    public event SynchIPDrugReturnRequestCompletedEventHandler SynchIPDrugReturnRequestCompleted;
    
    /// <remarks/>
    public event SynchCancelDrugReturnRequestsCompletedEventHandler SynchCancelDrugReturnRequestsCompleted;
    
    /// <remarks/>
    public event GetInPatientInfoCompletedEventHandler GetInPatientInfoCompleted;
    
    /// <remarks/>
    public event GetIPDrugOrderCompletedEventHandler GetIPDrugOrderCompleted;
    
    /// <remarks/>
    public event GetDiagnosisCompletedEventHandler GetDiagnosisCompleted;
    
    /// <remarks/>
    public event UpdateFPHCompletedEventHandler UpdateFPHCompleted;
    
    /// <remarks/>
    public event YPZDBZCompletedEventHandler YPZDBZCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DataExchange", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string DataExchange(string paramxml) {
        object[] results = this.Invoke("DataExchange", new object[] {
                    paramxml});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDataExchange(string paramxml, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DataExchange", new object[] {
                    paramxml}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndDataExchange(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void DataExchangeAsync(string paramxml) {
        this.DataExchangeAsync(paramxml, null);
    }
    
    /// <remarks/>
    public void DataExchangeAsync(string paramxml, object userState) {
        if ((this.DataExchangeOperationCompleted == null)) {
            this.DataExchangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDataExchangeOperationCompleted);
        }
        this.InvokeAsync("DataExchange", new object[] {
                    paramxml}, this.DataExchangeOperationCompleted, userState);
    }
    
    private void OnDataExchangeOperationCompleted(object arg) {
        if ((this.DataExchangeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.DataExchangeCompleted(this, new DataExchangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SyncDrugBasicInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string SyncDrugBasicInfo(string input) {
        object[] results = this.Invoke("SyncDrugBasicInfo", new object[] {
                    input});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSyncDrugBasicInfo(string input, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SyncDrugBasicInfo", new object[] {
                    input}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndSyncDrugBasicInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void SyncDrugBasicInfoAsync(string input) {
        this.SyncDrugBasicInfoAsync(input, null);
    }
    
    /// <remarks/>
    public void SyncDrugBasicInfoAsync(string input, object userState) {
        if ((this.SyncDrugBasicInfoOperationCompleted == null)) {
            this.SyncDrugBasicInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSyncDrugBasicInfoOperationCompleted);
        }
        this.InvokeAsync("SyncDrugBasicInfo", new object[] {
                    input}, this.SyncDrugBasicInfoOperationCompleted, userState);
    }
    
    private void OnSyncDrugBasicInfoOperationCompleted(object arg) {
        if ((this.SyncDrugBasicInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SyncDrugBasicInfoCompleted(this, new SyncDrugBasicInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDrugExtenderInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string GetDrugExtenderInfo(string input) {
        object[] results = this.Invoke("GetDrugExtenderInfo", new object[] {
                    input});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetDrugExtenderInfo(string input, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetDrugExtenderInfo", new object[] {
                    input}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndGetDrugExtenderInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void GetDrugExtenderInfoAsync(string input) {
        this.GetDrugExtenderInfoAsync(input, null);
    }
    
    /// <remarks/>
    public void GetDrugExtenderInfoAsync(string input, object userState) {
        if ((this.GetDrugExtenderInfoOperationCompleted == null)) {
            this.GetDrugExtenderInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDrugExtenderInfoOperationCompleted);
        }
        this.InvokeAsync("GetDrugExtenderInfo", new object[] {
                    input}, this.GetDrugExtenderInfoOperationCompleted, userState);
    }
    
    private void OnGetDrugExtenderInfoOperationCompleted(object arg) {
        if ((this.GetDrugExtenderInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetDrugExtenderInfoCompleted(this, new GetDrugExtenderInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SynchDeptPharmacyDrugRelation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string SynchDeptPharmacyDrugRelation(string input) {
        object[] results = this.Invoke("SynchDeptPharmacyDrugRelation", new object[] {
                    input});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSynchDeptPharmacyDrugRelation(string input, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SynchDeptPharmacyDrugRelation", new object[] {
                    input}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndSynchDeptPharmacyDrugRelation(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void SynchDeptPharmacyDrugRelationAsync(string input) {
        this.SynchDeptPharmacyDrugRelationAsync(input, null);
    }
    
    /// <remarks/>
    public void SynchDeptPharmacyDrugRelationAsync(string input, object userState) {
        if ((this.SynchDeptPharmacyDrugRelationOperationCompleted == null)) {
            this.SynchDeptPharmacyDrugRelationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSynchDeptPharmacyDrugRelationOperationCompleted);
        }
        this.InvokeAsync("SynchDeptPharmacyDrugRelation", new object[] {
                    input}, this.SynchDeptPharmacyDrugRelationOperationCompleted, userState);
    }
    
    private void OnSynchDeptPharmacyDrugRelationOperationCompleted(object arg) {
        if ((this.SynchDeptPharmacyDrugRelationCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SynchDeptPharmacyDrugRelationCompleted(this, new SynchDeptPharmacyDrugRelationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SynchDrugPrice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string SynchDrugPrice(string input) {
        object[] results = this.Invoke("SynchDrugPrice", new object[] {
                    input});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSynchDrugPrice(string input, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SynchDrugPrice", new object[] {
                    input}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndSynchDrugPrice(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void SynchDrugPriceAsync(string input) {
        this.SynchDrugPriceAsync(input, null);
    }
    
    /// <remarks/>
    public void SynchDrugPriceAsync(string input, object userState) {
        if ((this.SynchDrugPriceOperationCompleted == null)) {
            this.SynchDrugPriceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSynchDrugPriceOperationCompleted);
        }
        this.InvokeAsync("SynchDrugPrice", new object[] {
                    input}, this.SynchDrugPriceOperationCompleted, userState);
    }
    
    private void OnSynchDrugPriceOperationCompleted(object arg) {
        if ((this.SynchDrugPriceCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SynchDrugPriceCompleted(this, new SynchDrugPriceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDrugInventory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string GetDrugInventory(string input) {
        object[] results = this.Invoke("GetDrugInventory", new object[] {
                    input});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetDrugInventory(string input, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetDrugInventory", new object[] {
                    input}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndGetDrugInventory(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void GetDrugInventoryAsync(string input) {
        this.GetDrugInventoryAsync(input, null);
    }
    
    /// <remarks/>
    public void GetDrugInventoryAsync(string input, object userState) {
        if ((this.GetDrugInventoryOperationCompleted == null)) {
            this.GetDrugInventoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDrugInventoryOperationCompleted);
        }
        this.InvokeAsync("GetDrugInventory", new object[] {
                    input}, this.GetDrugInventoryOperationCompleted, userState);
    }
    
    private void OnGetDrugInventoryOperationCompleted(object arg) {
        if ((this.GetDrugInventoryCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetDrugInventoryCompleted(this, new GetDrugInventoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryOPDrugWindowRequest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string QueryOPDrugWindowRequest(string input) {
        object[] results = this.Invoke("QueryOPDrugWindowRequest", new object[] {
                    input});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginQueryOPDrugWindowRequest(string input, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("QueryOPDrugWindowRequest", new object[] {
                    input}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndQueryOPDrugWindowRequest(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void QueryOPDrugWindowRequestAsync(string input) {
        this.QueryOPDrugWindowRequestAsync(input, null);
    }
    
    /// <remarks/>
    public void QueryOPDrugWindowRequestAsync(string input, object userState) {
        if ((this.QueryOPDrugWindowRequestOperationCompleted == null)) {
            this.QueryOPDrugWindowRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryOPDrugWindowRequestOperationCompleted);
        }
        this.InvokeAsync("QueryOPDrugWindowRequest", new object[] {
                    input}, this.QueryOPDrugWindowRequestOperationCompleted, userState);
    }
    
    private void OnQueryOPDrugWindowRequestOperationCompleted(object arg) {
        if ((this.QueryOPDrugWindowRequestCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.QueryOPDrugWindowRequestCompleted(this, new QueryOPDrugWindowRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryOPDrugSendRequest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string QueryOPDrugSendRequest(string input) {
        object[] results = this.Invoke("QueryOPDrugSendRequest", new object[] {
                    input});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginQueryOPDrugSendRequest(string input, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("QueryOPDrugSendRequest", new object[] {
                    input}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndQueryOPDrugSendRequest(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void QueryOPDrugSendRequestAsync(string input) {
        this.QueryOPDrugSendRequestAsync(input, null);
    }
    
    /// <remarks/>
    public void QueryOPDrugSendRequestAsync(string input, object userState) {
        if ((this.QueryOPDrugSendRequestOperationCompleted == null)) {
            this.QueryOPDrugSendRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryOPDrugSendRequestOperationCompleted);
        }
        this.InvokeAsync("QueryOPDrugSendRequest", new object[] {
                    input}, this.QueryOPDrugSendRequestOperationCompleted, userState);
    }
    
    private void OnQueryOPDrugSendRequestOperationCompleted(object arg) {
        if ((this.QueryOPDrugSendRequestCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.QueryOPDrugSendRequestCompleted(this, new QueryOPDrugSendRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SyncOPFeeReturnStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string SyncOPFeeReturnStatus(string input) {
        object[] results = this.Invoke("SyncOPFeeReturnStatus", new object[] {
                    input});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSyncOPFeeReturnStatus(string input, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SyncOPFeeReturnStatus", new object[] {
                    input}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndSyncOPFeeReturnStatus(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void SyncOPFeeReturnStatusAsync(string input) {
        this.SyncOPFeeReturnStatusAsync(input, null);
    }
    
    /// <remarks/>
    public void SyncOPFeeReturnStatusAsync(string input, object userState) {
        if ((this.SyncOPFeeReturnStatusOperationCompleted == null)) {
            this.SyncOPFeeReturnStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSyncOPFeeReturnStatusOperationCompleted);
        }
        this.InvokeAsync("SyncOPFeeReturnStatus", new object[] {
                    input}, this.SyncOPFeeReturnStatusOperationCompleted, userState);
    }
    
    private void OnSyncOPFeeReturnStatusOperationCompleted(object arg) {
        if ((this.SyncOPFeeReturnStatusCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SyncOPFeeReturnStatusCompleted(this, new SyncOPFeeReturnStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SyncOPDrugSendRequest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string SyncOPDrugSendRequest(string input) {
        object[] results = this.Invoke("SyncOPDrugSendRequest", new object[] {
                    input});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSyncOPDrugSendRequest(string input, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SyncOPDrugSendRequest", new object[] {
                    input}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndSyncOPDrugSendRequest(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void SyncOPDrugSendRequestAsync(string input) {
        this.SyncOPDrugSendRequestAsync(input, null);
    }
    
    /// <remarks/>
    public void SyncOPDrugSendRequestAsync(string input, object userState) {
        if ((this.SyncOPDrugSendRequestOperationCompleted == null)) {
            this.SyncOPDrugSendRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSyncOPDrugSendRequestOperationCompleted);
        }
        this.InvokeAsync("SyncOPDrugSendRequest", new object[] {
                    input}, this.SyncOPDrugSendRequestOperationCompleted, userState);
    }
    
    private void OnSyncOPDrugSendRequestOperationCompleted(object arg) {
        if ((this.SyncOPDrugSendRequestCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SyncOPDrugSendRequestCompleted(this, new SyncOPDrugSendRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryOPDrugReturnRequest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string QueryOPDrugReturnRequest(string input) {
        object[] results = this.Invoke("QueryOPDrugReturnRequest", new object[] {
                    input});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginQueryOPDrugReturnRequest(string input, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("QueryOPDrugReturnRequest", new object[] {
                    input}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndQueryOPDrugReturnRequest(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void QueryOPDrugReturnRequestAsync(string input) {
        this.QueryOPDrugReturnRequestAsync(input, null);
    }
    
    /// <remarks/>
    public void QueryOPDrugReturnRequestAsync(string input, object userState) {
        if ((this.QueryOPDrugReturnRequestOperationCompleted == null)) {
            this.QueryOPDrugReturnRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryOPDrugReturnRequestOperationCompleted);
        }
        this.InvokeAsync("QueryOPDrugReturnRequest", new object[] {
                    input}, this.QueryOPDrugReturnRequestOperationCompleted, userState);
    }
    
    private void OnQueryOPDrugReturnRequestOperationCompleted(object arg) {
        if ((this.QueryOPDrugReturnRequestCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.QueryOPDrugReturnRequestCompleted(this, new QueryOPDrugReturnRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SynchOPDrugReturnRequest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string SynchOPDrugReturnRequest(string input) {
        object[] results = this.Invoke("SynchOPDrugReturnRequest", new object[] {
                    input});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSynchOPDrugReturnRequest(string input, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SynchOPDrugReturnRequest", new object[] {
                    input}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndSynchOPDrugReturnRequest(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void SynchOPDrugReturnRequestAsync(string input) {
        this.SynchOPDrugReturnRequestAsync(input, null);
    }
    
    /// <remarks/>
    public void SynchOPDrugReturnRequestAsync(string input, object userState) {
        if ((this.SynchOPDrugReturnRequestOperationCompleted == null)) {
            this.SynchOPDrugReturnRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSynchOPDrugReturnRequestOperationCompleted);
        }
        this.InvokeAsync("SynchOPDrugReturnRequest", new object[] {
                    input}, this.SynchOPDrugReturnRequestOperationCompleted, userState);
    }
    
    private void OnSynchOPDrugReturnRequestOperationCompleted(object arg) {
        if ((this.SynchOPDrugReturnRequestCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SynchOPDrugReturnRequestCompleted(this, new SynchOPDrugReturnRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryIPDrugSendRequest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string QueryIPDrugSendRequest(string input) {
        object[] results = this.Invoke("QueryIPDrugSendRequest", new object[] {
                    input});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginQueryIPDrugSendRequest(string input, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("QueryIPDrugSendRequest", new object[] {
                    input}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndQueryIPDrugSendRequest(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void QueryIPDrugSendRequestAsync(string input) {
        this.QueryIPDrugSendRequestAsync(input, null);
    }
    
    /// <remarks/>
    public void QueryIPDrugSendRequestAsync(string input, object userState) {
        if ((this.QueryIPDrugSendRequestOperationCompleted == null)) {
            this.QueryIPDrugSendRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryIPDrugSendRequestOperationCompleted);
        }
        this.InvokeAsync("QueryIPDrugSendRequest", new object[] {
                    input}, this.QueryIPDrugSendRequestOperationCompleted, userState);
    }
    
    private void OnQueryIPDrugSendRequestOperationCompleted(object arg) {
        if ((this.QueryIPDrugSendRequestCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.QueryIPDrugSendRequestCompleted(this, new QueryIPDrugSendRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SynchIPDrugSendRequest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string SynchIPDrugSendRequest(string input) {
        object[] results = this.Invoke("SynchIPDrugSendRequest", new object[] {
                    input});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSynchIPDrugSendRequest(string input, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SynchIPDrugSendRequest", new object[] {
                    input}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndSynchIPDrugSendRequest(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void SynchIPDrugSendRequestAsync(string input) {
        this.SynchIPDrugSendRequestAsync(input, null);
    }
    
    /// <remarks/>
    public void SynchIPDrugSendRequestAsync(string input, object userState) {
        if ((this.SynchIPDrugSendRequestOperationCompleted == null)) {
            this.SynchIPDrugSendRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSynchIPDrugSendRequestOperationCompleted);
        }
        this.InvokeAsync("SynchIPDrugSendRequest", new object[] {
                    input}, this.SynchIPDrugSendRequestOperationCompleted, userState);
    }
    
    private void OnSynchIPDrugSendRequestOperationCompleted(object arg) {
        if ((this.SynchIPDrugSendRequestCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SynchIPDrugSendRequestCompleted(this, new SynchIPDrugSendRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SynchCancelDrugSendRequests", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string SynchCancelDrugSendRequests(string input) {
        object[] results = this.Invoke("SynchCancelDrugSendRequests", new object[] {
                    input});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSynchCancelDrugSendRequests(string input, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SynchCancelDrugSendRequests", new object[] {
                    input}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndSynchCancelDrugSendRequests(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void SynchCancelDrugSendRequestsAsync(string input) {
        this.SynchCancelDrugSendRequestsAsync(input, null);
    }
    
    /// <remarks/>
    public void SynchCancelDrugSendRequestsAsync(string input, object userState) {
        if ((this.SynchCancelDrugSendRequestsOperationCompleted == null)) {
            this.SynchCancelDrugSendRequestsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSynchCancelDrugSendRequestsOperationCompleted);
        }
        this.InvokeAsync("SynchCancelDrugSendRequests", new object[] {
                    input}, this.SynchCancelDrugSendRequestsOperationCompleted, userState);
    }
    
    private void OnSynchCancelDrugSendRequestsOperationCompleted(object arg) {
        if ((this.SynchCancelDrugSendRequestsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SynchCancelDrugSendRequestsCompleted(this, new SynchCancelDrugSendRequestsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryIPDrugReturnRequest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string QueryIPDrugReturnRequest(string input) {
        object[] results = this.Invoke("QueryIPDrugReturnRequest", new object[] {
                    input});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginQueryIPDrugReturnRequest(string input, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("QueryIPDrugReturnRequest", new object[] {
                    input}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndQueryIPDrugReturnRequest(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void QueryIPDrugReturnRequestAsync(string input) {
        this.QueryIPDrugReturnRequestAsync(input, null);
    }
    
    /// <remarks/>
    public void QueryIPDrugReturnRequestAsync(string input, object userState) {
        if ((this.QueryIPDrugReturnRequestOperationCompleted == null)) {
            this.QueryIPDrugReturnRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryIPDrugReturnRequestOperationCompleted);
        }
        this.InvokeAsync("QueryIPDrugReturnRequest", new object[] {
                    input}, this.QueryIPDrugReturnRequestOperationCompleted, userState);
    }
    
    private void OnQueryIPDrugReturnRequestOperationCompleted(object arg) {
        if ((this.QueryIPDrugReturnRequestCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.QueryIPDrugReturnRequestCompleted(this, new QueryIPDrugReturnRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SynchIPDrugReturnRequest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string SynchIPDrugReturnRequest(string input) {
        object[] results = this.Invoke("SynchIPDrugReturnRequest", new object[] {
                    input});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSynchIPDrugReturnRequest(string input, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SynchIPDrugReturnRequest", new object[] {
                    input}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndSynchIPDrugReturnRequest(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void SynchIPDrugReturnRequestAsync(string input) {
        this.SynchIPDrugReturnRequestAsync(input, null);
    }
    
    /// <remarks/>
    public void SynchIPDrugReturnRequestAsync(string input, object userState) {
        if ((this.SynchIPDrugReturnRequestOperationCompleted == null)) {
            this.SynchIPDrugReturnRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSynchIPDrugReturnRequestOperationCompleted);
        }
        this.InvokeAsync("SynchIPDrugReturnRequest", new object[] {
                    input}, this.SynchIPDrugReturnRequestOperationCompleted, userState);
    }
    
    private void OnSynchIPDrugReturnRequestOperationCompleted(object arg) {
        if ((this.SynchIPDrugReturnRequestCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SynchIPDrugReturnRequestCompleted(this, new SynchIPDrugReturnRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SynchCancelDrugReturnRequests", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string SynchCancelDrugReturnRequests(string input) {
        object[] results = this.Invoke("SynchCancelDrugReturnRequests", new object[] {
                    input});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSynchCancelDrugReturnRequests(string input, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SynchCancelDrugReturnRequests", new object[] {
                    input}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndSynchCancelDrugReturnRequests(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void SynchCancelDrugReturnRequestsAsync(string input) {
        this.SynchCancelDrugReturnRequestsAsync(input, null);
    }
    
    /// <remarks/>
    public void SynchCancelDrugReturnRequestsAsync(string input, object userState) {
        if ((this.SynchCancelDrugReturnRequestsOperationCompleted == null)) {
            this.SynchCancelDrugReturnRequestsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSynchCancelDrugReturnRequestsOperationCompleted);
        }
        this.InvokeAsync("SynchCancelDrugReturnRequests", new object[] {
                    input}, this.SynchCancelDrugReturnRequestsOperationCompleted, userState);
    }
    
    private void OnSynchCancelDrugReturnRequestsOperationCompleted(object arg) {
        if ((this.SynchCancelDrugReturnRequestsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SynchCancelDrugReturnRequestsCompleted(this, new SynchCancelDrugReturnRequestsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInPatientInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string GetInPatientInfo(string input) {
        object[] results = this.Invoke("GetInPatientInfo", new object[] {
                    input});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetInPatientInfo(string input, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetInPatientInfo", new object[] {
                    input}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndGetInPatientInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void GetInPatientInfoAsync(string input) {
        this.GetInPatientInfoAsync(input, null);
    }
    
    /// <remarks/>
    public void GetInPatientInfoAsync(string input, object userState) {
        if ((this.GetInPatientInfoOperationCompleted == null)) {
            this.GetInPatientInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInPatientInfoOperationCompleted);
        }
        this.InvokeAsync("GetInPatientInfo", new object[] {
                    input}, this.GetInPatientInfoOperationCompleted, userState);
    }
    
    private void OnGetInPatientInfoOperationCompleted(object arg) {
        if ((this.GetInPatientInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetInPatientInfoCompleted(this, new GetInPatientInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetIPDrugOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string GetIPDrugOrder(string input) {
        object[] results = this.Invoke("GetIPDrugOrder", new object[] {
                    input});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetIPDrugOrder(string input, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetIPDrugOrder", new object[] {
                    input}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndGetIPDrugOrder(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void GetIPDrugOrderAsync(string input) {
        this.GetIPDrugOrderAsync(input, null);
    }
    
    /// <remarks/>
    public void GetIPDrugOrderAsync(string input, object userState) {
        if ((this.GetIPDrugOrderOperationCompleted == null)) {
            this.GetIPDrugOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetIPDrugOrderOperationCompleted);
        }
        this.InvokeAsync("GetIPDrugOrder", new object[] {
                    input}, this.GetIPDrugOrderOperationCompleted, userState);
    }
    
    private void OnGetIPDrugOrderOperationCompleted(object arg) {
        if ((this.GetIPDrugOrderCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetIPDrugOrderCompleted(this, new GetIPDrugOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDiagnosis", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string GetDiagnosis(string input) {
        object[] results = this.Invoke("GetDiagnosis", new object[] {
                    input});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetDiagnosis(string input, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetDiagnosis", new object[] {
                    input}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndGetDiagnosis(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void GetDiagnosisAsync(string input) {
        this.GetDiagnosisAsync(input, null);
    }
    
    /// <remarks/>
    public void GetDiagnosisAsync(string input, object userState) {
        if ((this.GetDiagnosisOperationCompleted == null)) {
            this.GetDiagnosisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDiagnosisOperationCompleted);
        }
        this.InvokeAsync("GetDiagnosis", new object[] {
                    input}, this.GetDiagnosisOperationCompleted, userState);
    }
    
    private void OnGetDiagnosisOperationCompleted(object arg) {
        if ((this.GetDiagnosisCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetDiagnosisCompleted(this, new GetDiagnosisCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateFPH", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string UpdateFPH(string input) {
        object[] results = this.Invoke("UpdateFPH", new object[] {
                    input});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUpdateFPH(string input, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("UpdateFPH", new object[] {
                    input}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndUpdateFPH(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void UpdateFPHAsync(string input) {
        this.UpdateFPHAsync(input, null);
    }
    
    /// <remarks/>
    public void UpdateFPHAsync(string input, object userState) {
        if ((this.UpdateFPHOperationCompleted == null)) {
            this.UpdateFPHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateFPHOperationCompleted);
        }
        this.InvokeAsync("UpdateFPH", new object[] {
                    input}, this.UpdateFPHOperationCompleted, userState);
    }
    
    private void OnUpdateFPHOperationCompleted(object arg) {
        if ((this.UpdateFPHCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.UpdateFPHCompleted(this, new UpdateFPHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/YPZDBZ", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string YPZDBZ() {
        object[] results = this.Invoke("YPZDBZ", new object[0]);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginYPZDBZ(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("YPZDBZ", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string EndYPZDBZ(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void YPZDBZAsync() {
        this.YPZDBZAsync(null);
    }
    
    /// <remarks/>
    public void YPZDBZAsync(object userState) {
        if ((this.YPZDBZOperationCompleted == null)) {
            this.YPZDBZOperationCompleted = new System.Threading.SendOrPostCallback(this.OnYPZDBZOperationCompleted);
        }
        this.InvokeAsync("YPZDBZ", new object[0], this.YPZDBZOperationCompleted, userState);
    }
    
    private void OnYPZDBZOperationCompleted(object arg) {
        if ((this.YPZDBZCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.YPZDBZCompleted(this, new YPZDBZCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void DataExchangeCompletedEventHandler(object sender, DataExchangeCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DataExchangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal DataExchangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void SyncDrugBasicInfoCompletedEventHandler(object sender, SyncDrugBasicInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SyncDrugBasicInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SyncDrugBasicInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void GetDrugExtenderInfoCompletedEventHandler(object sender, GetDrugExtenderInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetDrugExtenderInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetDrugExtenderInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void SynchDeptPharmacyDrugRelationCompletedEventHandler(object sender, SynchDeptPharmacyDrugRelationCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SynchDeptPharmacyDrugRelationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SynchDeptPharmacyDrugRelationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void SynchDrugPriceCompletedEventHandler(object sender, SynchDrugPriceCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SynchDrugPriceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SynchDrugPriceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void GetDrugInventoryCompletedEventHandler(object sender, GetDrugInventoryCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetDrugInventoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetDrugInventoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void QueryOPDrugWindowRequestCompletedEventHandler(object sender, QueryOPDrugWindowRequestCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class QueryOPDrugWindowRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal QueryOPDrugWindowRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void QueryOPDrugSendRequestCompletedEventHandler(object sender, QueryOPDrugSendRequestCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class QueryOPDrugSendRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal QueryOPDrugSendRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void SyncOPFeeReturnStatusCompletedEventHandler(object sender, SyncOPFeeReturnStatusCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SyncOPFeeReturnStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SyncOPFeeReturnStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void SyncOPDrugSendRequestCompletedEventHandler(object sender, SyncOPDrugSendRequestCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SyncOPDrugSendRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SyncOPDrugSendRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void QueryOPDrugReturnRequestCompletedEventHandler(object sender, QueryOPDrugReturnRequestCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class QueryOPDrugReturnRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal QueryOPDrugReturnRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void SynchOPDrugReturnRequestCompletedEventHandler(object sender, SynchOPDrugReturnRequestCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SynchOPDrugReturnRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SynchOPDrugReturnRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void QueryIPDrugSendRequestCompletedEventHandler(object sender, QueryIPDrugSendRequestCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class QueryIPDrugSendRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal QueryIPDrugSendRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void SynchIPDrugSendRequestCompletedEventHandler(object sender, SynchIPDrugSendRequestCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SynchIPDrugSendRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SynchIPDrugSendRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void SynchCancelDrugSendRequestsCompletedEventHandler(object sender, SynchCancelDrugSendRequestsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SynchCancelDrugSendRequestsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SynchCancelDrugSendRequestsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void QueryIPDrugReturnRequestCompletedEventHandler(object sender, QueryIPDrugReturnRequestCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class QueryIPDrugReturnRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal QueryIPDrugReturnRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void SynchIPDrugReturnRequestCompletedEventHandler(object sender, SynchIPDrugReturnRequestCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SynchIPDrugReturnRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SynchIPDrugReturnRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void SynchCancelDrugReturnRequestsCompletedEventHandler(object sender, SynchCancelDrugReturnRequestsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SynchCancelDrugReturnRequestsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SynchCancelDrugReturnRequestsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void GetInPatientInfoCompletedEventHandler(object sender, GetInPatientInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetInPatientInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetInPatientInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void GetIPDrugOrderCompletedEventHandler(object sender, GetIPDrugOrderCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetIPDrugOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetIPDrugOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void GetDiagnosisCompletedEventHandler(object sender, GetDiagnosisCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetDiagnosisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetDiagnosisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void UpdateFPHCompletedEventHandler(object sender, UpdateFPHCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class UpdateFPHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal UpdateFPHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void YPZDBZCompletedEventHandler(object sender, YPZDBZCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class YPZDBZCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal YPZDBZCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
