//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChargeInterface.PivasCharge {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://196.57.57.76/PivasWebService.asmx", ConfigurationName="PivasCharge.PivasWebServiceSoap")]
    public interface PivasWebServiceSoap {
        
        // CODEGEN: 命名空间 http://196.57.57.76/PivasWebService.asmx 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://196.57.57.76/PivasWebService.asmx/HelloWorld", ReplyAction="*")]
        ChargeInterface.PivasCharge.HelloWorldResponse HelloWorld(ChargeInterface.PivasCharge.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://196.57.57.76/PivasWebService.asmx 的元素名称 Groupno 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://196.57.57.76/PivasWebService.asmx/Charge", ReplyAction="*")]
        ChargeInterface.PivasCharge.ChargeResponse Charge(ChargeInterface.PivasCharge.ChargeRequest request);
        
        // CODEGEN: 命名空间 http://196.57.57.76/PivasWebService.asmx 的元素名称 p_group_no 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://196.57.57.76/PivasWebService.asmx/BackPre", ReplyAction="*")]
        ChargeInterface.PivasCharge.BackPreResponse BackPre(ChargeInterface.PivasCharge.BackPreRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://196.57.57.76/PivasWebService.asmx", Order=0)]
        public ChargeInterface.PivasCharge.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ChargeInterface.PivasCharge.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://196.57.57.76/PivasWebService.asmx", Order=0)]
        public ChargeInterface.PivasCharge.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ChargeInterface.PivasCharge.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://196.57.57.76/PivasWebService.asmx")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChargeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Charge", Namespace="http://196.57.57.76/PivasWebService.asmx", Order=0)]
        public ChargeInterface.PivasCharge.ChargeRequestBody Body;
        
        public ChargeRequest() {
        }
        
        public ChargeRequest(ChargeInterface.PivasCharge.ChargeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://196.57.57.76/PivasWebService.asmx")]
    public partial class ChargeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Groupno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string infusionDT;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UserCode;
        
        public ChargeRequestBody() {
        }
        
        public ChargeRequestBody(string Groupno, string infusionDT, string UserCode) {
            this.Groupno = Groupno;
            this.infusionDT = infusionDT;
            this.UserCode = UserCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChargeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChargeResponse", Namespace="http://196.57.57.76/PivasWebService.asmx", Order=0)]
        public ChargeInterface.PivasCharge.ChargeResponseBody Body;
        
        public ChargeResponse() {
        }
        
        public ChargeResponse(ChargeInterface.PivasCharge.ChargeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://196.57.57.76/PivasWebService.asmx")]
    public partial class ChargeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ChargeResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string hismsg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string hisret;
        
        public ChargeResponseBody() {
        }
        
        public ChargeResponseBody(string ChargeResult, string hismsg, string hisret) {
            this.ChargeResult = ChargeResult;
            this.hismsg = hismsg;
            this.hisret = hisret;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BackPreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BackPre", Namespace="http://196.57.57.76/PivasWebService.asmx", Order=0)]
        public ChargeInterface.PivasCharge.BackPreRequestBody Body;
        
        public BackPreRequest() {
        }
        
        public BackPreRequest(ChargeInterface.PivasCharge.BackPreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://196.57.57.76/PivasWebService.asmx")]
    public partial class BackPreRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string p_group_no;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string prm_EXEC_DOCTOR;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string prm_jujueyy;
        
        public BackPreRequestBody() {
        }
        
        public BackPreRequestBody(string p_group_no, string prm_EXEC_DOCTOR, string prm_jujueyy) {
            this.p_group_no = p_group_no;
            this.prm_EXEC_DOCTOR = prm_EXEC_DOCTOR;
            this.prm_jujueyy = prm_jujueyy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BackPreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BackPreResponse", Namespace="http://196.57.57.76/PivasWebService.asmx", Order=0)]
        public ChargeInterface.PivasCharge.BackPreResponseBody Body;
        
        public BackPreResponse() {
        }
        
        public BackPreResponse(ChargeInterface.PivasCharge.BackPreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://196.57.57.76/PivasWebService.asmx")]
    public partial class BackPreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BackPreResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PRM_DATABUFFER;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PRM_APPCODE;
        
        public BackPreResponseBody() {
        }
        
        public BackPreResponseBody(string BackPreResult, string PRM_DATABUFFER, string PRM_APPCODE) {
            this.BackPreResult = BackPreResult;
            this.PRM_DATABUFFER = PRM_DATABUFFER;
            this.PRM_APPCODE = PRM_APPCODE;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PivasWebServiceSoapChannel : ChargeInterface.PivasCharge.PivasWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PivasWebServiceSoapClient : System.ServiceModel.ClientBase<ChargeInterface.PivasCharge.PivasWebServiceSoap>, ChargeInterface.PivasCharge.PivasWebServiceSoap {
        
        public PivasWebServiceSoapClient() {
        }
        
        public PivasWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PivasWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PivasWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PivasWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChargeInterface.PivasCharge.HelloWorldResponse ChargeInterface.PivasCharge.PivasWebServiceSoap.HelloWorld(ChargeInterface.PivasCharge.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ChargeInterface.PivasCharge.HelloWorldRequest inValue = new ChargeInterface.PivasCharge.HelloWorldRequest();
            inValue.Body = new ChargeInterface.PivasCharge.HelloWorldRequestBody();
            ChargeInterface.PivasCharge.HelloWorldResponse retVal = ((ChargeInterface.PivasCharge.PivasWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChargeInterface.PivasCharge.ChargeResponse ChargeInterface.PivasCharge.PivasWebServiceSoap.Charge(ChargeInterface.PivasCharge.ChargeRequest request) {
            return base.Channel.Charge(request);
        }
        
        public string Charge(string Groupno, string infusionDT, string UserCode, out string hismsg, out string hisret) {
            ChargeInterface.PivasCharge.ChargeRequest inValue = new ChargeInterface.PivasCharge.ChargeRequest();
            inValue.Body = new ChargeInterface.PivasCharge.ChargeRequestBody();
            inValue.Body.Groupno = Groupno;
            inValue.Body.infusionDT = infusionDT;
            inValue.Body.UserCode = UserCode;
            ChargeInterface.PivasCharge.ChargeResponse retVal = ((ChargeInterface.PivasCharge.PivasWebServiceSoap)(this)).Charge(inValue);
            hismsg = retVal.Body.hismsg;
            hisret = retVal.Body.hisret;
            return retVal.Body.ChargeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChargeInterface.PivasCharge.BackPreResponse ChargeInterface.PivasCharge.PivasWebServiceSoap.BackPre(ChargeInterface.PivasCharge.BackPreRequest request) {
            return base.Channel.BackPre(request);
        }
        
        public string BackPre(string p_group_no, string prm_EXEC_DOCTOR, string prm_jujueyy, out string PRM_DATABUFFER, out string PRM_APPCODE) {
            ChargeInterface.PivasCharge.BackPreRequest inValue = new ChargeInterface.PivasCharge.BackPreRequest();
            inValue.Body = new ChargeInterface.PivasCharge.BackPreRequestBody();
            inValue.Body.p_group_no = p_group_no;
            inValue.Body.prm_EXEC_DOCTOR = prm_EXEC_DOCTOR;
            inValue.Body.prm_jujueyy = prm_jujueyy;
            ChargeInterface.PivasCharge.BackPreResponse retVal = ((ChargeInterface.PivasCharge.PivasWebServiceSoap)(this)).BackPre(inValue);
            PRM_DATABUFFER = retVal.Body.PRM_DATABUFFER;
            PRM_APPCODE = retVal.Body.PRM_APPCODE;
            return retVal.Body.BackPreResult;
        }
    }
}
