//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using ChargeInterface.Properties;
using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// 此源代码由 wsdl 自动生成, Version=4.6.1055.0。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="OrderManagerServiceSoap", Namespace="http://tempuri.org/")]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ResponseContainerBase))]
public partial class OrderManagerService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback ExeConfirmOutOrderOperationCompleted;
    
    private System.Threading.SendOrPostCallback CancelConfirmOutOrderOperationCompleted;
    
    private System.Threading.SendOrPostCallback BatExeConfirmInOrderOperationCompleted;
    
    private System.Threading.SendOrPostCallback ExeConfirmInOrderOperationCompleted;
    
    private System.Threading.SendOrPostCallback ChargeUpItemOperationCompleted;
    
    private System.Threading.SendOrPostCallback ChargeInOrderOperationCompleted;
    
    /// <remarks/>
    public OrderManagerService() {
        this.Url = Settings.Default.GDHQ_Service_Address;//从配置文件中加载服务地址
        //this.Url = "http://hisorderexecutionwebservice.saas.jd120.com/OrderManagerService.asmx";
    }
    
    /// <remarks/>
    public event ExeConfirmOutOrderCompletedEventHandler ExeConfirmOutOrderCompleted;
    
    /// <remarks/>
    public event CancelConfirmOutOrderCompletedEventHandler CancelConfirmOutOrderCompleted;
    
    /// <remarks/>
    public event BatExeConfirmInOrderCompletedEventHandler BatExeConfirmInOrderCompleted;
    
    /// <remarks/>
    public event ExeConfirmInOrderCompletedEventHandler ExeConfirmInOrderCompleted;
    
    /// <remarks/>
    public event ChargeUpItemCompletedEventHandler ChargeUpItemCompleted;
    
    /// <remarks/>
    public event ChargeInOrderCompletedEventHandler ChargeInOrderCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ExeConfirmOutOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public ResponseContainerOfBoolean ExeConfirmOutOrder(string ordId, string userId) {
        object[] results = this.Invoke("ExeConfirmOutOrder", new object[] {
                    ordId,
                    userId});
        return ((ResponseContainerOfBoolean)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginExeConfirmOutOrder(string ordId, string userId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ExeConfirmOutOrder", new object[] {
                    ordId,
                    userId}, callback, asyncState);
    }
    
    /// <remarks/>
    public ResponseContainerOfBoolean EndExeConfirmOutOrder(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ResponseContainerOfBoolean)(results[0]));
    }
    
    /// <remarks/>
    public void ExeConfirmOutOrderAsync(string ordId, string userId) {
        this.ExeConfirmOutOrderAsync(ordId, userId, null);
    }
    
    /// <remarks/>
    public void ExeConfirmOutOrderAsync(string ordId, string userId, object userState) {
        if ((this.ExeConfirmOutOrderOperationCompleted == null)) {
            this.ExeConfirmOutOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExeConfirmOutOrderOperationCompleted);
        }
        this.InvokeAsync("ExeConfirmOutOrder", new object[] {
                    ordId,
                    userId}, this.ExeConfirmOutOrderOperationCompleted, userState);
    }
    
    private void OnExeConfirmOutOrderOperationCompleted(object arg) {
        if ((this.ExeConfirmOutOrderCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ExeConfirmOutOrderCompleted(this, new ExeConfirmOutOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CancelConfirmOutOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public ResponseContainerOfBoolean CancelConfirmOutOrder(string ordId, string userId) {
        object[] results = this.Invoke("CancelConfirmOutOrder", new object[] {
                    ordId,
                    userId});
        return ((ResponseContainerOfBoolean)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCancelConfirmOutOrder(string ordId, string userId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CancelConfirmOutOrder", new object[] {
                    ordId,
                    userId}, callback, asyncState);
    }
    
    /// <remarks/>
    public ResponseContainerOfBoolean EndCancelConfirmOutOrder(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ResponseContainerOfBoolean)(results[0]));
    }
    
    /// <remarks/>
    public void CancelConfirmOutOrderAsync(string ordId, string userId) {
        this.CancelConfirmOutOrderAsync(ordId, userId, null);
    }
    
    /// <remarks/>
    public void CancelConfirmOutOrderAsync(string ordId, string userId, object userState) {
        if ((this.CancelConfirmOutOrderOperationCompleted == null)) {
            this.CancelConfirmOutOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelConfirmOutOrderOperationCompleted);
        }
        this.InvokeAsync("CancelConfirmOutOrder", new object[] {
                    ordId,
                    userId}, this.CancelConfirmOutOrderOperationCompleted, userState);
    }
    
    private void OnCancelConfirmOutOrderOperationCompleted(object arg) {
        if ((this.CancelConfirmOutOrderCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CancelConfirmOutOrderCompleted(this, new CancelConfirmOutOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BatExeConfirmInOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public ResponseContainerOfString BatExeConfirmInOrder(string ordIdStr, string userId) {
        object[] results = this.Invoke("BatExeConfirmInOrder", new object[] {
                    ordIdStr,
                    userId});
        return ((ResponseContainerOfString)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginBatExeConfirmInOrder(string ordIdStr, string userId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("BatExeConfirmInOrder", new object[] {
                    ordIdStr,
                    userId}, callback, asyncState);
    }
    
    /// <remarks/>
    public ResponseContainerOfString EndBatExeConfirmInOrder(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ResponseContainerOfString)(results[0]));
    }
    
    /// <remarks/>
    public void BatExeConfirmInOrderAsync(string ordIdStr, string userId) {
        this.BatExeConfirmInOrderAsync(ordIdStr, userId, null);
    }
    
    /// <remarks/>
    public void BatExeConfirmInOrderAsync(string ordIdStr, string userId, object userState) {
        if ((this.BatExeConfirmInOrderOperationCompleted == null)) {
            this.BatExeConfirmInOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBatExeConfirmInOrderOperationCompleted);
        }
        this.InvokeAsync("BatExeConfirmInOrder", new object[] {
                    ordIdStr,
                    userId}, this.BatExeConfirmInOrderOperationCompleted, userState);
    }
    
    private void OnBatExeConfirmInOrderOperationCompleted(object arg) {
        if ((this.BatExeConfirmInOrderCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.BatExeConfirmInOrderCompleted(this, new BatExeConfirmInOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ExeConfirmInOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public ResponseContainerOfString ExeConfirmInOrder(string[] ordIds, string userId) {
        object[] results = this.Invoke("ExeConfirmInOrder", new object[] {
                    ordIds,
                    userId});
        return ((ResponseContainerOfString)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginExeConfirmInOrder(string[] ordIds, string userId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ExeConfirmInOrder", new object[] {
                    ordIds,
                    userId}, callback, asyncState);
    }
    
    /// <remarks/>
    public ResponseContainerOfString EndExeConfirmInOrder(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ResponseContainerOfString)(results[0]));
    }
    
    /// <remarks/>
    public void ExeConfirmInOrderAsync(string[] ordIds, string userId) {
        this.ExeConfirmInOrderAsync(ordIds, userId, null);
    }
    
    /// <remarks/>
    public void ExeConfirmInOrderAsync(string[] ordIds, string userId, object userState) {
        if ((this.ExeConfirmInOrderOperationCompleted == null)) {
            this.ExeConfirmInOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExeConfirmInOrderOperationCompleted);
        }
        this.InvokeAsync("ExeConfirmInOrder", new object[] {
                    ordIds,
                    userId}, this.ExeConfirmInOrderOperationCompleted, userState);
    }
    
    private void OnExeConfirmInOrderOperationCompleted(object arg) {
        if ((this.ExeConfirmInOrderCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ExeConfirmInOrderCompleted(this, new ExeConfirmInOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChargeUpItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public ResponseContainerOfBoolean ChargeUpItem(string inpatiId, ChargeItemInfo itemInfo, string execOrgId, string operatorId) {
        object[] results = this.Invoke("ChargeUpItem", new object[] {
                    inpatiId,
                    itemInfo,
                    execOrgId,
                    operatorId});
        return ((ResponseContainerOfBoolean)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginChargeUpItem(string inpatiId, ChargeItemInfo itemInfo, string execOrgId, string operatorId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ChargeUpItem", new object[] {
                    inpatiId,
                    itemInfo,
                    execOrgId,
                    operatorId}, callback, asyncState);
    }
    
    /// <remarks/>
    public ResponseContainerOfBoolean EndChargeUpItem(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ResponseContainerOfBoolean)(results[0]));
    }
    
    /// <remarks/>
    public void ChargeUpItemAsync(string inpatiId, ChargeItemInfo itemInfo, string execOrgId, string operatorId) {
        this.ChargeUpItemAsync(inpatiId, itemInfo, execOrgId, operatorId, null);
    }
    
    /// <remarks/>
    public void ChargeUpItemAsync(string inpatiId, ChargeItemInfo itemInfo, string execOrgId, string operatorId, object userState) {
        if ((this.ChargeUpItemOperationCompleted == null)) {
            this.ChargeUpItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChargeUpItemOperationCompleted);
        }
        this.InvokeAsync("ChargeUpItem", new object[] {
                    inpatiId,
                    itemInfo,
                    execOrgId,
                    operatorId}, this.ChargeUpItemOperationCompleted, userState);
    }
    
    private void OnChargeUpItemOperationCompleted(object arg) {
        if ((this.ChargeUpItemCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ChargeUpItemCompleted(this, new ChargeUpItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChargeInOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string ChargeInOrder(string inpatiId, string itemId, string quantity, string execOrgId, string operatorId) {
        object[] results = this.Invoke("ChargeInOrder", new object[] {
                    inpatiId,
                    itemId,
                    quantity,
                    execOrgId,
                    operatorId});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginChargeInOrder(string inpatiId, string itemId, string quantity, string execOrgId, string operatorId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ChargeInOrder", new object[] {
                    inpatiId,
                    itemId,
                    quantity,
                    execOrgId,
                    operatorId}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndChargeInOrder(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void ChargeInOrderAsync(string inpatiId, string itemId, string quantity, string execOrgId, string operatorId) {
        this.ChargeInOrderAsync(inpatiId, itemId, quantity, execOrgId, operatorId, null);
    }
    
    /// <remarks/>
    public void ChargeInOrderAsync(string inpatiId, string itemId, string quantity, string execOrgId, string operatorId, object userState) {
        if ((this.ChargeInOrderOperationCompleted == null)) {
            this.ChargeInOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChargeInOrderOperationCompleted);
        }
        this.InvokeAsync("ChargeInOrder", new object[] {
                    inpatiId,
                    itemId,
                    quantity,
                    execOrgId,
                    operatorId}, this.ChargeInOrderOperationCompleted, userState);
    }
    
    private void OnChargeInOrderOperationCompleted(object arg) {
        if ((this.ChargeInOrderCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ChargeInOrderCompleted(this, new ChargeInOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class ResponseContainerOfBoolean : ResponseContainerBase {
    
    private bool responseContentField;
    
    /// <remarks/>
    public bool ResponseContent {
        get {
            return this.responseContentField;
        }
        set {
            this.responseContentField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ResponseContainerOfString))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ResponseContainerOfBoolean))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class ResponseContainerBase {
    
    private bool hasExceptionField;
    
    private string exceptionMessageField;
    
    private string exceptionStackTraceField;
    
    /// <remarks/>
    public bool HasException {
        get {
            return this.hasExceptionField;
        }
        set {
            this.hasExceptionField = value;
        }
    }
    
    /// <remarks/>
    public string ExceptionMessage {
        get {
            return this.exceptionMessageField;
        }
        set {
            this.exceptionMessageField = value;
        }
    }
    
    /// <remarks/>
    public string ExceptionStackTrace {
        get {
            return this.exceptionStackTraceField;
        }
        set {
            this.exceptionStackTraceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class ChargeItemInfo {
    
    private string itemIdField;
    
    private int quantityField;
    
    /// <remarks/>
    public string ItemId {
        get {
            return this.itemIdField;
        }
        set {
            this.itemIdField = value;
        }
    }
    
    /// <remarks/>
    public int Quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class ResponseContainerOfString : ResponseContainerBase {
    
    private string responseContentField;
    
    /// <remarks/>
    public string ResponseContent {
        get {
            return this.responseContentField;
        }
        set {
            this.responseContentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void ExeConfirmOutOrderCompletedEventHandler(object sender, ExeConfirmOutOrderCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ExeConfirmOutOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ExeConfirmOutOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ResponseContainerOfBoolean Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ResponseContainerOfBoolean)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void CancelConfirmOutOrderCompletedEventHandler(object sender, CancelConfirmOutOrderCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CancelConfirmOutOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CancelConfirmOutOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ResponseContainerOfBoolean Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ResponseContainerOfBoolean)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void BatExeConfirmInOrderCompletedEventHandler(object sender, BatExeConfirmInOrderCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class BatExeConfirmInOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal BatExeConfirmInOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ResponseContainerOfString Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ResponseContainerOfString)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void ExeConfirmInOrderCompletedEventHandler(object sender, ExeConfirmInOrderCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ExeConfirmInOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ExeConfirmInOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ResponseContainerOfString Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ResponseContainerOfString)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void ChargeUpItemCompletedEventHandler(object sender, ChargeUpItemCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ChargeUpItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ChargeUpItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ResponseContainerOfBoolean Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ResponseContainerOfBoolean)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void ChargeInOrderCompletedEventHandler(object sender, ChargeInOrderCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ChargeInOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ChargeInOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
