//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenService.WCFS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFS.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData1", ReplyAction="http://tempuri.org/IService1/GetData1Response")]
        string GetData1(string ip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData1", ReplyAction="http://tempuri.org/IService1/GetData1Response")]
        System.Threading.Tasks.Task<string> GetData1Async(string ip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDrugData", ReplyAction="http://tempuri.org/IService1/GetDrugDataResponse")]
        string GetDrugData(string uip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDrugData", ReplyAction="http://tempuri.org/IService1/GetDrugDataResponse")]
        System.Threading.Tasks.Task<string> GetDrugDataAsync(string uip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDrugTest", ReplyAction="http://tempuri.org/IService1/GetDrugTestResponse")]
        string GetDrugTest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDrugTest", ReplyAction="http://tempuri.org/IService1/GetDrugTestResponse")]
        System.Threading.Tasks.Task<string> GetDrugTestAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ScreenService.WCFS.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ScreenService.WCFS.IService1>, ScreenService.WCFS.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData1(string ip) {
            return base.Channel.GetData1(ip);
        }
        
        public System.Threading.Tasks.Task<string> GetData1Async(string ip) {
            return base.Channel.GetData1Async(ip);
        }
        
        public string GetDrugData(string uip) {
            return base.Channel.GetDrugData(uip);
        }
        
        public System.Threading.Tasks.Task<string> GetDrugDataAsync(string uip) {
            return base.Channel.GetDrugDataAsync(uip);
        }
        
        public string GetDrugTest() {
            return base.Channel.GetDrugTest();
        }
        
        public System.Threading.Tasks.Task<string> GetDrugTestAsync() {
            return base.Channel.GetDrugTestAsync();
        }
    }
}
