//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.8689
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.CompactFramework.Design.Data 2.0.50727.8689 版自动生成。
// 
namespace EDA.WebReference {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public Service1() {
            this.Url = "http://192.168.12.37:8089/Service1.asmx";
        }

        public Service1(String serway)
        {
            this.Url = serway;
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Login(string Employeid, string pwd) {
            object[] results = this.Invoke("Login", new object[] {
                        Employeid,
                        pwd});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLogin(string Employeid, string pwd, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Login", new object[] {
                        Employeid,
                        pwd}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndLogin(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QRLabelNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int QRLabelNo(string DEmployeeID, string LabelNo, string CheckPro) {
            object[] results = this.Invoke("QRLabelNo", new object[] {
                        DEmployeeID,
                        LabelNo,
                        CheckPro});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginQRLabelNo(string DEmployeeID, string LabelNo, string CheckPro, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("QRLabelNo", new object[] {
                        DEmployeeID,
                        LabelNo,
                        CheckPro}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndQRLabelNo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SigleLableNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SigleLableNo(string DEmployeeID, string LabelNos, string CheckPro, int ivs) {
            object[] results = this.Invoke("SigleLableNo", new object[] {
                        DEmployeeID,
                        LabelNos,
                        CheckPro,
                        ivs});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSigleLableNo(string DEmployeeID, string LabelNos, string CheckPro, int ivs, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SigleLableNo", new object[] {
                        DEmployeeID,
                        LabelNos,
                        CheckPro,
                        ivs}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndSigleLableNo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Rongji", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Rongji(string DEmployeeID, string LabelNo) {
            object[] results = this.Invoke("Rongji", new object[] {
                        DEmployeeID,
                        LabelNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRongji(string DEmployeeID, string LabelNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Rongji", new object[] {
                        DEmployeeID,
                        LabelNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndRongji(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RongMei", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RongMei(string DEmployeeID, string LabelNo) {
            object[] results = this.Invoke("RongMei", new object[] {
                        DEmployeeID,
                        LabelNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRongMei(string DEmployeeID, string LabelNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RongMei", new object[] {
                        DEmployeeID,
                        LabelNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndRongMei(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PaiYao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PaiYao(string DEmployeeID, string LabelNo) {
            object[] results = this.Invoke("PaiYao", new object[] {
                        DEmployeeID,
                        LabelNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPaiYao(string DEmployeeID, string LabelNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("PaiYao", new object[] {
                        DEmployeeID,
                        LabelNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndPaiYao(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PeiZhi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PeiZhi(string DEmployeeID, string LabelNo) {
            object[] results = this.Invoke("PeiZhi", new object[] {
                        DEmployeeID,
                        LabelNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPeiZhi(string DEmployeeID, string LabelNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("PeiZhi", new object[] {
                        DEmployeeID,
                        LabelNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndPeiZhi(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DaBao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DaBao(string DEmployeeID, string LabelNo) {
            object[] results = this.Invoke("DaBao", new object[] {
                        DEmployeeID,
                        LabelNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDaBao(string DEmployeeID, string LabelNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DaBao", new object[] {
                        DEmployeeID,
                        LabelNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndDaBao(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/JinCang", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string JinCang(string DEmployeeID, string LabelNo) {
            object[] results = this.Invoke("JinCang", new object[] {
                        DEmployeeID,
                        LabelNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginJinCang(string DEmployeeID, string LabelNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("JinCang", new object[] {
                        DEmployeeID,
                        LabelNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndJinCang(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChuCang", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ChuCang(string DEmployeeID, string LabelNo) {
            object[] results = this.Invoke("ChuCang", new object[] {
                        DEmployeeID,
                        LabelNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginChuCang(string DEmployeeID, string LabelNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ChuCang", new object[] {
                        DEmployeeID,
                        LabelNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndChuCang(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Qianshou", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Qianshou(string DEmployeeID, string LabelNo) {
            object[] results = this.Invoke("Qianshou", new object[] {
                        DEmployeeID,
                        LabelNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginQianshou(string DEmployeeID, string LabelNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Qianshou", new object[] {
                        DEmployeeID,
                        LabelNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndQianshou(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LableInfor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LableInfor(string LabelNo, string OtherCondition) {
            object[] results = this.Invoke("LableInfor", new object[] {
                        LabelNo,
                        OtherCondition});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLableInfor(string LabelNo, string OtherCondition, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("LableInfor", new object[] {
                        LabelNo,
                        OtherCondition}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndLableInfor(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DrugInfor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DrugInfor(string LabelNo) {
            object[] results = this.Invoke("DrugInfor", new object[] {
                        LabelNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDrugInfor(string LabelNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DrugInfor", new object[] {
                        LabelNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndDrugInfor(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AllDrugNum", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AllDrugNum(string DEmployeeID, string Checkpro) {
            object[] results = this.Invoke("AllDrugNum", new object[] {
                        DEmployeeID,
                        Checkpro});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAllDrugNum(string DEmployeeID, string Checkpro, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AllDrugNum", new object[] {
                        DEmployeeID,
                        Checkpro}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndAllDrugNum(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DwardInfor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DwardInfor(string demployeeid, string checkpro, string date) {
            object[] results = this.Invoke("DwardInfor", new object[] {
                        demployeeid,
                        checkpro,
                        date});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDwardInfor(string demployeeid, string checkpro, string date, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DwardInfor", new object[] {
                        demployeeid,
                        checkpro,
                        date}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndDwardInfor(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InforByDward", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InforByDward(string checkpro, string date, string wardname) {
            object[] results = this.Invoke("InforByDward", new object[] {
                        checkpro,
                        date,
                        wardname});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInforByDward(string checkpro, string date, string wardname, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InforByDward", new object[] {
                        checkpro,
                        date,
                        wardname}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndInforByDward(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectStepDetail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SelectStepDetail(string labelno) {
            object[] results = this.Invoke("SelectStepDetail", new object[] {
                        labelno});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSelectStepDetail(string labelno, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SelectStepDetail", new object[] {
                        labelno}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndSelectStepDetail(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReturnErrorType", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ReturnErrorType(string errorstep) {
            object[] results = this.Invoke("ReturnErrorType", new object[] {
                        errorstep});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginReturnErrorType(string errorstep, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ReturnErrorType", new object[] {
                        errorstep}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndReturnErrorType(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddErrorRecord", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AddErrorRecord(string labelno, string errstep, string errDid, string fid, string etime, string etype) {
            object[] results = this.Invoke("AddErrorRecord", new object[] {
                        labelno,
                        errstep,
                        errDid,
                        fid,
                        etime,
                        etype});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAddErrorRecord(string labelno, string errstep, string errDid, string fid, string etime, string etype, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AddErrorRecord", new object[] {
                        labelno,
                        errstep,
                        errDid,
                        fid,
                        etime,
                        etype}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndAddErrorRecord(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ShowDward", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ShowDward() {
            object[] results = this.Invoke("ShowDward", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginShowDward(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ShowDward", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndShowDward(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
